### ISSUE TITLE
Frontend needs update

### ISSUE THREAD

**Issue by marefr** [grafana/simple-datasource-backend#1]
Should use [DataSourceWithBackend](https://github.com/grafana/grafana/blob/ab8305fcb9ccf826c6607c19a4bbc24ee891b55d/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts).

**Comment by bergquist** [comment]
@marefr I don't understand what that means. care to elaborate?

**Comment by marefr** [comment]
Some examples of other data sources using this:
- https://github.com/grafana/google-sheets-datasource/blob/master/src/DataSource.ts
- https://github.com/grafana/test-datasource/blob/master/src/DataSource.ts

Basically you don't have to implement querying and testing of a data source

**Comment by marefr** [comment]
Fixed by #3
