### ISSUE TITLE
Can't install the plugin in a Grafana Docker container

### ISSUE THREAD

**Issue by ilangleben19** [grafana/simple-datasource-backend#12]
I'm completely unable to install the plugin in a Grafana 7.0.1 container of Docker. I cloned the repository into the plugins folder and ran all build commands with no errors.

In a Docker shell, when I run `grafana-cli plugins ls`, I see that the plugin is technically installed, but I don't see it as a Data Source or Plugin option in the Grafana web interface. As an extra test, I added a bit of code to the Go backend which writes a simple message to a text file. Restarting Grafana didn't make the text file appear, but manually calling the executable did make it appear.

What can I do? Is there any other information I can provide that could be of help?

**Comment by marefr** [comment]
This is a template repository and used when building a backend plugin, see [tutorial](https://grafana.com/tutorials/build-a-data-source-backend-plugin/#1), but should work anyway. Are you installing plugins using [this method](https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container)? 

Check the logs, maybe you've hit by Grafana [requires backend plugins to be signed](https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/#backend-plugins).

**Comment by ilangleben19** [comment]
Yeah, it was the signing thing. I really hope they plan to add something about signing your plugin to that tutorial page very soon - I wasted easily 6 hours trying to figure it out.

**Comment by marefr** [comment]
@ilangleben19 yes, we're planning to add that. Thanks

**Comment by marefr** [comment]
Opened an issue to fix this https://github.com/grafana/tutorials/issues/65
